### ISSUE TITLE
Being racist

### ISSUE THREAD

**Issue by khaled-0** [Iyxan23/sw-bot#3]
https://github.com/Iyxan23/sw-bot/blob/5bc9f21f62880f7229f46b3a8dfce2066b24b60d/src/commands/fun_stuff.rs#L95

This produces 0% for your id .
Very unfair and rude and rigged and cheated and geh and

**Comment by iyxan23** [comment]
> https://github.com/Iyxan23/sw-bot/blob/5bc9f21f62880f7229f46b3a8dfce2066b24b60d/src/commands/fun_stuff.rs#L95
> 
> This produces 0% for your id . Very unfair and rude and rigged and cheated and geh and

it was purely a coincidence

**Comment by iyxan23** [comment]
:trollface:
